CCMS-UCSD/GNPS_Workflows

- metabolomics-snets-v2/metabolomics-snets-v2/binding.xml
- metabolomics-snets-v2/metabolomics-snets-v2/flow.xml
- metabolomics-snets-v2/metabolomics-snets-v2/tool.xml
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/convert_networks_to_graphml.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/find_related_public_data_wrapper.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/ming_fileio_library.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/ming_gnps_library.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/ming_numerical_utilities.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/ming_parallel_library.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/ming_proteosafe_library.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/ming_psm_library.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/ming_spectrum_library.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/ming_sptxt_library.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/molecular_network_filtering_library.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/molecular_network_library.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/mscluster_wrapper.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/network_utils.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/spectrum_alignment.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/topology_library.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/topology_proteosafe_wrapper.py
1. Migrate to python3
2. Cleanup pklbin output for clustering
3. Bug fixes for topology
4. Bug fixes for MASST
> Metabolomics v2 Bug Fixes

- feature-based-molecular-networking/tools/feature-based-molecular-networking/scripts/xcms_formatter.py
> Fix for XCMS converter

- molnetenhancer/tools/molnetenhancer/chemClass2Network.py
- molnetenhancer/tools/molnetenhancer/molnetenhancer.py
Reverts CCMS-UCSD/GNPS_Workflows#32
> Revert "MolNetEnhancer MS2LDA update"

- molnetenhancer/tools/molnetenhancer/chemClass2Network.py
- molnetenhancer/tools/molnetenhancer/molnetenhancer.py
test cases:
failed - https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=aaff02c11f514d8db203b31b6b5058c1 (fundamental conflict with networkx.read_graphml)
passed - https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=fe0eab89ab55416c82cdf3e6bba96014
passed - https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=1626073f6f224862bc852139a5c61be7
passed - https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=1b96965e4629442dbedd39ec5e25bd4f
passed - https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=eac9a6df8cda40d588fd51451f44bc02
passed - https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=b6862e7f6f9f49169a4f496edc586f26
> updated molnetenhancer logic for ms2lda

- molnetenhancer/tools/molnetenhancer/chemClass2Network.py
- molnetenhancer/tools/molnetenhancer/molnetenhancer.py
resolved merge conflict between older production version and new development version. new code needs testing #136 #135
> resolved version-merge conflicts

- molnetenhancer/tools/molnetenhancer/chemClass2Network.py
- molnetenhancer/tools/molnetenhancer/molnetenhancer.py
chemClass2Network.py:
request_Varquest_file() had missing parameter (directory)
add_Chemical_Info() if statements include None type and str type of 'None'
molnetenhancer.py:
added print('No MS2LDA Op')
> minor syntax changes

- feature-based-molecular-networking/tools/feature-based-molecular-networking/scripts/metaboscape_formatter.py
Fix the mapping between quant table and MGF for non PASEF data.
> MetaboScape: Fix for quant table / MGF matching

- search_single_spectrum/tools/search_single_spectrum/MASST_validator.py
> adding single spectrum validator

- README.md
- feature-based-molecular-networking/tools/feature-based-molecular-networking/scripts/xcms_formatter.py
Fix for the python 3.7 error message.
> [FBMN][IIN] Update XCMS formatter 

- molnetenhancer/tools/molnetenhancer/chemClass2Network.py
… parsing corrupt gnpslib files
> added error_bad_lines = False to gnpslib parsing to avoid errors when parsing corrupt gnpslib files

- molnetenhancer/tools/molnetenhancer/chemClass2Network.py
Testing here: 
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=c8f759f0d5464d4fbcce29bd64ddb63e
> [WIP] bug fix for structure conversion

- molecular-librarysearch-gc/molecular-librarysearch-gc/tool.xml
- molecular-librarysearch-gc/tools/molecularsearch-gc/add_mshub_data.py
Addressing: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/285
> GC bug fix for making balance score file optional

- msms-chooser/tools/msms-chooser/prepare_library_addtions_gnps_collections.py
add K adducts to MSMS-Chooser script for selection
> add K adducts to script

- feature-based-molecular-networking/feature-based-molecular-networking/input.xml
- feature-based-molecular-networking/feature-based-molecular-networking/tool.xml
- feature-based-molecular-networking/tools/feature-based-molecular-networking/scripts/run_qiime2.py
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/390
> adding ability to run qiime2 with different distance metrics

- qemistree/Makefile
- qemistree/qemistree/result.xml
> Qemistree Explicit Download Button

- qemistree/README.md
- qemistree/qemistree/input.xml
- qemistree/tools/qemistree/qemistree.py
This PR:
- fixes CLI commands
- homogenized output naming convention (using dashes instead of underscores)
- add refresh-cache instruction for future updates to new qemistree releases
- adds tooltip for metadata column input
> Qemistree tree

- qemistree/qemistree/result.xml
- workflow-integration-misc-tests/test_tasks.csv
- adds test task
- updates summary view
> Qemistree summary

- openms/README.md
- upd README links to build-env.sh and conda-env.yaml files
Signed-off-by: Abi Sarvepalli <abisarvepalli@gmail.com>
> CCMS+OpenMS Workflow

- merge_networks_polarity/Makefile
Merging Networks, fixing merging when its multigraphs:
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/497
> Merge polarity fix

- qemistree/qemistree/input.xml
- qemistree/qemistree/tool.xml
- qemistree/tools/qemistree/qemistree.py
> adding ioinization mode in advanced options + changing default

- merge_networks_polarity/Makefile
- merge_networks_polarity/merge_networks_polarity/input.xml
- merge_networks_polarity/merge_networks_polarity/tool.xml
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/516
> Adding Merge Polarity Options

- chemdir/Makefile
- chemdir/chemdir/binding.xml
- chemdir/chemdir/flow.xml
- chemdir/chemdir/input.xml
- chemdir/chemdir/result.xml
- chemdir/chemdir/tool.xml
- chemdir/test-integration-workflow/test_tasks.csv
- chemdir/tools/chemdir/calculate_chemdir.py
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/579
> adding chemdir workflow

- search_single_spectrum/Makefile
- search_single_spectrum/tools/search_single_spectrum/find_related_public_data_wrapper.py
- search_single_spectrum/tools/search_single_spectrum/reanalysis_preparation.py
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/514
> MASST - None Title Fixed

- search_single_spectrum/Makefile
- search_single_spectrum/search_single_spectrum/result.xml
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/587
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/502
> Adding USI Links to MASST Searches

- feature-based-molecular-networking/feature-based-molecular-networking/result.xml
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/608
> FBMN - adding analog results to download

- search_single_spectrum/search_single_spectrum/input.xml
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/630
> [MASST] Deactivate parameter selection for Find Related Datasets

- molecular-librarysearch-gc/molecular-librarysearch-gc/result.xml
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/640
> Adding qiime2 output to gc

- qemistree/tools/qemistree/qemistree.py
Updates made with @anupriyatripathi
> BUG: Removing iTOL in favor of Empress

- mshub-gc/Makefile
- mshub-gc/mshub-gc/input.xml
- mshub-gc/mshub-gc/result.xml
- mshub-gc/test-integration-workflow/test_tasks.csv
- mshub-gc/test/test.py
- mshub-gc/tools/mshub-gc/process_gc.py
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/639
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/638
> [MSHub] Adding in RTMean and Linkouts to LCMS Viewer

- metabolomics-snets-v2/Makefile
- metabolomics-snets-v2/metabolomics-snets-v2/result.xml
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/628
> [Classical] Fixing Dereplicator+ Linkout

- feature-based-molecular-networking/Makefile
- feature-based-molecular-networking/tools/feature-based-molecular-networking/scripts/ming_spectrum_library.py
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/664
> [Classic Molecular Networking] Adding in MSLEVEL into output MGF

- qemistree/qemistree/result.xml
Fixes the qiime2 view error on workflow
> update qemistree filename

- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/getGNPS_library_annotations.py
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/693
> [Networking] Fixing NP Classifier Output

- feature-based-molecular-networking/feature-based-molecular-networking/result.xml
- metabolomics-snets-v2/metabolomics-snets-v2/result.xml
- molecular-librarysearch-gc/molecular-librarysearch-gc/result.xml
- qemistree/qemistree/result.xml
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/684
> [CORS] New new CORS service for Qiime2

- feature-based-molecular-networking/feature-based-molecular-networking/result.xml
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/691
> [FBMN] Linking to new plotter hostname

- feature-based-molecular-networking/Makefile
- feature-based-molecular-networking/feature-based-molecular-networking/result.xml
- metabolomics-snets-v2/Makefile
- metabolomics-snets-v2/metabolomics-snets-v2/result.xml
- shared_code/molecular_network_filtering_library.py
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/703
> [FBMN] Top K sorting to make sure top hit gets in the graphml Network

- feature-based-molecular-networking/Makefile
- feature-based-molecular-networking/feature-based-molecular-networking/tool.xml
- feature-based-molecular-networking/test-integration-workflow/test_tasks.csv
- metabolomics-snets-v2/Makefile
- metabolomics-snets-v2/test-integration-workflow/test_tasks.csv
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/getGNPS_library_annotations.py
- requirements.txt
- search_single_spectrum/Makefile
- search_single_spectrum/test-integration-workflow/test_tasks.csv
- search_single_spectrum/tools/search_single_spectrum/foodomics_track.py
- shared_code/ming_gnps_library.py
- shared_code/molecular_network_filtering_library.py
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/709
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/707
> [FBMN] Fixing bugs in top k and missing identifications

- search_single_spectrum/search_single_spectrum/tool.xml
- search_single_spectrum/test/test_foodomics.py
- search_single_spectrum/tools/search_single_spectrum/foodomics_track.py
I hope this fixes the issue in #757 
We now use an argument to input the local foodomics metadata table
> [foodmasst] argument for local file

- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/getGNPS_library_annotations.py
adding molecular formula calculation
> Adding Molecular Formula to Library Results

- metabolomics-snets-v2/metabolomics-snets-v2/input.xml
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/molecular_networking_parallel_step_wrapper.py
- metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/prep_molecular_networking_parameters.py
- shared_code/molecular_network_filtering_library.py
> [Networking] Order of operations when no edges output

- ms2lda_motifdb/Makefile
- ms2lda_motifdb/tools/ms2lda_motifdb/ms2lda_runfull.py
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/779
> [MS2LDA] Update to fix SSL Cert expiration

- ms2lda_motifdb/test/test.py
- ms2lda_motifdb/tools/ms2lda_motifdb/ms2lda_runfull.py
Hi Ming,
I tried to add some test for MotifDB calls. It's the `test_ms2lda_motifdb()` method inside ms2lda_motifdb/test/test.py. Is this the correct way to add this so it will be called by the git action? Any help or advice would be appreciated, thanks!
Also I fixed that one line in ms2lda_runfull.py as it wouldn't run before. There are some code duplications between ms2lda_runfull.py and test.py, will refactor all this at some point to tidy it up properly.
Joe
> Added some MotifDB test

- feature-based-molecular-networking/Makefile
- feature-based-molecular-networking/tools/feature-based-molecular-networking/scripts/openms_formatter.py
Fixes: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/817
> [FBMN] Updating OpenMS Format

- .github/workflows/workflow-unit-fbmn.yml
- feature-based-molecular-networking/test/test_workflow_components.py
- feature-based-molecular-networking/test/unittest.cfg
- npclassifier/test/Makefile
- template_workflow/test/Makefile
Fixed: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/834
> [FBMN] Adding more error reporting for additional edges
